version: 2.1

orbs:
  slack: circleci/slack@3.4.2

workflows:
  version: 2

  build-deploy:
    jobs:
      - build:
          context: docker-login
          filters:
            branches:
              only:
                - master
      - deploy:
          context: ssh-login
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - notify_build:
          requires:
            - build

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t retrotool/proxy:$CIRCLE_SHA1 -t retrotool/proxy:latest .
      - run:
          name: Login to DockerHub
          command: docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
      - run:
          name: Push commit image to DockerHub
          command: docker push retrotool/proxy:$CIRCLE_SHA1
      - run:
          name: Push latest image to DockerHub
          command: docker push retrotool/proxy:latest

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh $SSH_USER@$SSH_SERVER "./deploy.sh"

  notify_build:
    docker:
      - image: circleci/node:latest
    steps:
      - slack/notify:
          message: ":rocket: Docker image built -> retrotool/proxy:latest"
